import { createRouter as createTanStackRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

export function createRouter() {
	return createTanStackRouter({
		// routeTree will be regenerated by @tanstack/router-cli.
		routeTree: routeTree as any,
		scrollRestoration: true,
	});
}

export const router = createRouter();

declare module "@tanstack/react-router" {
	// eslint-disable-next-line @typescript-eslint/no-empty-interface
	interface Register {
		router: typeof router;
	}
}
