version: "3.9"
services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: openchat
      PGDATA: /var/lib/postgresql/data/pgdata
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=20"
      - "-c"
      - "max_replication_slots=20"
    ports:
      - "39029:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d openchat"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  electric:
    image: electricsql/electric:latest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/openchat?sslmode=disable
      SHADOW_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/openchat_shadow?sslmode=disable
      PG_PROXY_PASSWORD: dev-proxy-password
      ELECTRIC_INSECURE: "true"
      LOG_LEVEL: info
    ports:
      - "3010:3000"
      - "5133:5133"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pg_data:
