version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: openchat_pg
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: openchat
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:

