version: "3.9"

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: openchat
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d openchat"]
      interval: 10s
      timeout: 5s
      retries: 5

  electric:
    image: electricsql/electric:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/openchat?sslmode=disable
      SHADOW_DATABASE_URL: postgres://postgres:postgres@db:5432/openchat_shadow?sslmode=disable
      PG_PROXY_PASSWORD: dev-proxy-password
      ELECTRIC_INSECURE: "true"
    ports:
      - "3010:3000"
      - "5133:5133"

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - electric
    environment:
      SERVER_PORT: 3000
      WEB_PORT: 3001
      NEXT_PUBLIC_SERVER_URL: http://app:3000
      NEXT_PUBLIC_ELECTRIC_URL: http://electric:3000
      ELECTRIC_SERVICE_URL: http://electric:3000
    ports:
      - "3000:3000"
      - "3001:3001"
volumes:
  pg_data:
