version: "3.9"

services:
  server:
    build:
      context: ..
      dockerfile: Dockerfile
      target: server-runner
    image: openchat-server:latest
    restart: unless-stopped
    env_file:
      - ../apps/server/.env
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  web:
    build:
      context: ..
      dockerfile: Dockerfile
      target: web-runner
    image: openchat-web:latest
    restart: unless-stopped
    depends_on:
      - server
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_SERVER_URL: http://server:3000
    ports:
      - "3001:3001"

