name: Production Canary

on:
  push:
    branches:
      - main

jobs:
  prod-canary:
    name: Run production canary checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.2.21"

      - name: Run canary tests
        env:
          PROD_CONVEX_URL: ${{ secrets.CONVEX_URL }}
          CANARY_TIMEOUT_MS: "15000"
          CANARY_MAX_RETRIES: "5"
          CANARY_RETRY_DELAY_MS: "10000"
        run: bun ./scripts/prod-canary.ts
